#ifndef __HYSCAN_DB_RPC_H__
#define __HYSCAN_DB_RPC_H__

#include <urpc-types.h>

#define HYSCAN_DB_RPC_VERSION          (20160400)
#define HYSCAN_DB_RPC_STATUS_OK        (1)
#define HYSCAN_DB_RPC_STATUS_FAIL      (0)

enum
{
  HYSCAN_DB_RPC_PROC_VERSION = URPC_PROC_USER,
  HYSCAN_DB_RPC_PROC_GET_URI,
  HYSCAN_DB_RPC_PROC_GET_MOD_COUNT,
  HYSCAN_DB_RPC_PROC_IS_EXIST,
  HYSCAN_DB_RPC_PROC_PROJECT_LIST,
  HYSCAN_DB_RPC_PROC_PROJECT_OPEN,
  HYSCAN_DB_RPC_PROC_PROJECT_CREATE,
  HYSCAN_DB_RPC_PROC_PROJECT_REMOVE,
  HYSCAN_DB_RPC_PROC_PROJECT_GET_CTIME,
  HYSCAN_DB_RPC_PROC_PROJECT_PARAM_LIST,
  HYSCAN_DB_RPC_PROC_PROJECT_PARAM_OPEN,
  HYSCAN_DB_RPC_PROC_PROJECT_PARAM_REMOVE,
  HYSCAN_DB_RPC_PROC_TRACK_LIST,
  HYSCAN_DB_RPC_PROC_TRACK_OPEN,
  HYSCAN_DB_RPC_PROC_TRACK_CREATE,
  HYSCAN_DB_RPC_PROC_TRACK_REMOVE,
  HYSCAN_DB_RPC_PROC_TRACK_GET_CTIME,
  HYSCAN_DB_RPC_PROC_TRACK_PARAM_OPEN,
  HYSCAN_DB_RPC_PROC_CHANNEL_LIST,
  HYSCAN_DB_RPC_PROC_CHANNEL_OPEN,
  HYSCAN_DB_RPC_PROC_CHANNEL_CREATE,
  HYSCAN_DB_RPC_PROC_CHANNEL_REMOVE,
  HYSCAN_DB_RPC_PROC_CHANNEL_FINALIZE,
  HYSCAN_DB_RPC_PROC_CHANNEL_IS_WRITABLE,
  HYSCAN_DB_RPC_PROC_CHANNEL_PARAM_OPEN,
  HYSCAN_DB_RPC_PROC_CHANNEL_SET_CHUNK_SIZE,
  HYSCAN_DB_RPC_PROC_CHANNEL_SET_SAVE_TIME,
  HYSCAN_DB_RPC_PROC_CHANNEL_SET_SAVE_SIZE,
  HYSCAN_DB_RPC_PROC_CHANNEL_GET_DATA_RANGE,
  HYSCAN_DB_RPC_PROC_CHANNEL_ADD_DATA,
  HYSCAN_DB_RPC_PROC_CHANNEL_GET_DATA,
  HYSCAN_DB_RPC_PROC_CHANNEL_FIND_DATA,
  HYSCAN_DB_RPC_PROC_PARAM_OBJECT_LIST,
  HYSCAN_DB_RPC_PROC_PARAM_OBJECT_CREATE,
  HYSCAN_DB_RPC_PROC_PARAM_OBJECT_REMOVE,
  HYSCAN_DB_RPC_PROC_PARAM_OBJECT_GET_SCHEMA,
  HYSCAN_DB_RPC_PROC_PARAM_SET,
  HYSCAN_DB_RPC_PROC_PARAM_GET,
  HYSCAN_DB_RPC_PROC_CLOSE
};

enum
{
  HYSCAN_DB_RPC_PARAM_VERSION = URPC_PARAM_USER,
  HYSCAN_DB_RPC_PARAM_STATUS,
  HYSCAN_DB_RPC_PARAM_URI,
  HYSCAN_DB_RPC_PARAM_ID,
  HYSCAN_DB_RPC_PARAM_MOD_COUNT,
  HYSCAN_DB_RPC_PARAM_PROJECT_LIST,
  HYSCAN_DB_RPC_PARAM_PROJECT_NAME,
  HYSCAN_DB_RPC_PARAM_PROJECT_SCHEMA,
  HYSCAN_DB_RPC_PARAM_PROJECT_ID,
  HYSCAN_DB_RPC_PARAM_TRACK_LIST,
  HYSCAN_DB_RPC_PARAM_TRACK_NAME,
  HYSCAN_DB_RPC_PARAM_TRACK_SCHEMA,
  HYSCAN_DB_RPC_PARAM_TRACK_SCHEMA_ID,
  HYSCAN_DB_RPC_PARAM_TRACK_ID,
  HYSCAN_DB_RPC_PARAM_CHANNEL_LIST,
  HYSCAN_DB_RPC_PARAM_CHANNEL_NAME,
  HYSCAN_DB_RPC_PARAM_CHANNEL_SCHEMA_ID,
  HYSCAN_DB_RPC_PARAM_CHANNEL_ID,
  HYSCAN_DB_RPC_PARAM_PARAM_GROUP_LIST,
  HYSCAN_DB_RPC_PARAM_PARAM_OBJECT_LIST,
  HYSCAN_DB_RPC_PARAM_PARAM_OBJECT_NAME,
  HYSCAN_DB_RPC_PARAM_PARAM_OBJECT_SCHEMA,
  HYSCAN_DB_RPC_PARAM_PARAM_OBJECT_SCHEMA_ID,
  HYSCAN_DB_RPC_PARAM_PARAM_NAME,
  HYSCAN_DB_RPC_PARAM_PARAM_ID,
  HYSCAN_DB_RPC_PARAM_PARAM_DST_ID,
  HYSCAN_DB_RPC_PARAM_GROUP_NAME,
  HYSCAN_DB_RPC_PARAM_CHUNK_SIZE,
  HYSCAN_DB_RPC_PARAM_SAVE_TIME,
  HYSCAN_DB_RPC_PARAM_SAVE_SIZE,
  HYSCAN_DB_RPC_PARAM_TIME,
  HYSCAN_DB_RPC_PARAM_CTIME,
  HYSCAN_DB_RPC_PARAM_LTIME,
  HYSCAN_DB_RPC_PARAM_RTIME,
  HYSCAN_DB_RPC_PARAM_INDEX,
  HYSCAN_DB_RPC_PARAM_LINDEX,
  HYSCAN_DB_RPC_PARAM_RINDEX,
  HYSCAN_DB_RPC_PARAM_DATA,
  HYSCAN_DB_RPC_PARAM_TYPE,
  HYSCAN_DB_RPC_PARAM_VALUE,
  HYSCAN_DB_RPC_PARAM_SIZE,
};

#endif /* __HYSCAN_DB_RPC_H__ */
